global using static MakerPrompt.Shared.Utils.Enums;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Text.Json.Serialization;
global using System.Reflection;
global using System.Numerics;
global using MakerPrompt.Shared.Infrastructure;
global using MakerPrompt.Shared.Properties;
global using MakerPrompt.Shared.Services;
global using MakerPrompt.Shared.Models;
global using MakerPrompt.Shared.Utils;
global using Microsoft.JSInterop;