name: Deploy Blazor WASM

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  #   paths:
  #     - 'MakerPrompt.Blazor/**'
  # pull_request:
  #   branches: [main]

env:
  BLAZOR_PROJECT: 'MakerPrompt.Blazor/MakerPrompt.Blazor.csproj'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.15'

    - name: Publish Blazor WASM
      run: dotnet publish ${{ env.BLAZOR_PROJECT }} -c Release -o publish