name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-windows
        
    - name: Restore dependencies (Blazor)
      run: dotnet restore MakerPrompt.Blazor/MakerPrompt.Blazor.csproj

    - name: Build (Windows)
      run: dotnet build MakerPrompt.MAUI/MakerPrompt.MAUI.csproj -c Release -f net8.0-windows10.0.19041.0 -p:RuntimeIdentifierOverride=win-x64

    - name: Build (Blazor WebAssembly)
      run: dotnet build MakerPrompt.Blazor/MakerPrompt.Blazor.csproj -c Release --no-restore