name: Build MAUI Apps

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  MAUI_PROJECT: 'MakerPrompt.MAUI/MakerPrompt.MAUI.csproj'
  OUTPUT_DIR: 'publish'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-desktop
        dotnet workload install maui-android
        dotnet workload install maui-maccatalyst

    - name: Restore dependencies
      run: dotnet restore ${{ env.MAUI_PROJECT }}

    - name: Generate Version
      run: |
        echo "VERSION=$(date +%Y.%m.%d)" >> $GITHUB_ENV

    - name: Publish MAUI Windows
      continue-on-error: true
      run: dotnet publish ${{ env.MAUI_PROJECT }} -c Release -f net8.0-windows10.0.19041.0 -p:WindowsPackageType=None -o ${{ env.OUTPUT_DIR }}/windows 
          -p:ApplicationDisplayVersion=${{ VERSION }} 
          -p:ApplicationVersion=${{ VERSION }}

    - name: Upload Windows Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: ${{ env.OUTPUT_DIR }}/windows

    - name: Publish MAUI Android
      continue-on-error: true
      run: dotnet publish ${{ env.MAUI_PROJECT }} -c Release -f net8.0-android -o ${{ env.OUTPUT_DIR }}/android 
          -p:ApplicationDisplayVersion=${{ VERSION }} 
          -p:ApplicationVersion=${{ VERSION }}

    - name: Upload Android Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: ${{ env.OUTPUT_DIR }}/android

    - name: Publish MAUI MacCatalyst
      continue-on-error: true
      run: dotnet publish ${{ env.MAUI_PROJECT }} -c Release -f net8.0-maccatalyst -o ${{ env.OUTPUT_DIR }}/maccatalyst -p:CreatePackage=false
          -p:ApplicationDisplayVersion=${{ VERSION }} 
          -p:ApplicationVersion=${{ VERSION }}

    - name: Upload MacCatalyst Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: maccatalyst-app
        path: ${{ env.MAUI_PROJECT }}/bin/Release